initCmd: "make up"
endCmd: "make down"
beforeCmd:
afterCmd:
sets:
  - cmd:
    path: "./spring_dev"
    initCmd:
    endCmd:
    excludeDir:
      - "./spring_dev"
    waitMillisecond: 1000 # default 100
  - cmd:
    path: "./react_dev"
    initCmd: 
    endCmd:
    excludeDir:
      - "./react_dev"
    waitMillisecond: 1000 # default 100
  - cmd:
    path: "./go_dev"
    initCmd:
    endCmd:
    excludeDir:
      - "./go_dev"
    waitMillisecond: 1000 # default 100
