initCmd: "./cmd.sh rmi up"
endCmd: "./cmd.sh down"
beforeCmd:
afterCmd: "./cmd.sh rmi"
sets:
  - cmd: "./cmd.sh cmd"
    path: './spring_dev'
    initCmd:
    endCmd:
    excludeDir:
      - './spring_dev/.gradle'
      - './spring_dev/build'
      - './spring_dev/gradle'
#    waitMillisecond: 500 # default 100
