initCmd: "make up"
endCmd: "make down"
beforeCmd:
afterCmd: "bash ./cmd.sh rmi"
sets:
  - cmd: "bash ./cmd.sh build update"
    path: "./spring_dev"
    initCmd:
    endCmd:
    excludeDir:
      - "./spring_dev/.gradle"
      - "./spring_dev/build"
      - "./spring_dev/gradle"
      - "./spring_dev/out"
      - "./spring_dev/src/main/generated"
      - "./spring_dev/src/test"
    waitMillisecond: 1000 # default 100
  - cmd:
    path: "./react_dev"
    initCmd: "bash ./cmd.sh watch"
    endCmd:
    excludeDir:
      - "./react_dev"
    waitMillisecond: 1000 # default 100
  - cmd: "bash ./cmd.sh update"
    path: "./react_dev"
    initCmd:
    endCmd:
    excludeDir:
      - "./react_dev/node_modules"
      - "./react_dev/src"
    waitMillisecond: 1000 # default 100
  - cmd: "bash ./cmd.sh build update"
    path: "./go_dev"
    initCmd:
    endCmd:
    excludeDir:
      - "./go_dev/build"
    waitMillisecond: 1000 # default 100
  - cmd:
    path: "./angular_dev"
    initCmd: "bash ./cmd.sh watch"
    endCmd:
    excludeDir:
      - "./angular_dev"
    waitMillisecond: 1000 # default 100
  - cmd: "bash ./cmd.sh update"
    path: "./angular_dev"
    initCmd:
    endCmd:
    excludeDir:
      - "./angular_dev/node_modules"
      - "./angular_dev/.angular"
      - "./angular_dev/src"
    waitMillisecond: 1000 # default 100
