initCmd: "bash ./cmd.sh rmi up"
endCmd: "bash ./cmd.sh down"
beforeCmd:
afterCmd: "bash ./cmd.sh rmi"
sets:
  - cmd: "bash ./cmd.sh build update"
    path: "./spring_dev"
    initCmd: "bash ./cmd.sh build update"
    endCmd:
    excludeDir:
      - "./spring_dev/.gradle"
      - "./spring_dev/build"
      - "./spring_dev/gradle"
      - "./spring_dev/src/test"
    waitMillisecond: 1500 # default 100
