initCmd: "./cmd.sh rmi up"
endCmd: "./cmd.sh down"
beforeCmd:
afterCmd:
sets:
  - cmd:
    path: "./spring_dev"
    initCmd: "./cmd.sh build update"
    endCmd:
    excludeDir:
      - "./spring_dev"
#    waitMillisecond: 500 # default 100
