initCmd: "bash ./cmd.sh rmi up"
endCmd: "bash ./cmd.sh down"
beforeCmd:
afterCmd:
sets:
  - cmd:
    path: "./spring_dev"
    initCmd: "bash ./cmd.sh build update"
    endCmd:
    excludeDir:
      - "./spring_dev"
    waitMillisecond: 1000 # default 100
  - cmd:
    path: "./react_dev"
    initCmd: "bash ./cmd.sh build update"
    endCmd:
    excludeDir:
      - "./react_dev"
    waitMillisecond: 1000 # default 100
