initCmd: "make up"
endCmd: "make down"
beforeCmd:
afterCmd: "bash ./cmd.sh rmi"
sets:
  - cmd: "bash ./cmd.sh build update"
    path: "./spring_dev"
    initCmd:
    endCmd:
    excludeDir:
      - "./spring_dev/.gradle"
      - "./spring_dev/build"
      - "./spring_dev/gradle"
      - "./spring_dev/out"
      - "./spring_dev/src/main/generated"
      - "./spring_dev/src/test"
    waitMillisecond: 1000 # default 100
  - cmd: "bash ./cmd.sh build update"
    path: "./react_dev"
    initCmd: 
    endCmd:
    excludeDir:
      - "./react_dev/dist"
      - "./react_dev/node_modules"
    waitMillisecond: 1000 # default 100
