spring:
  redis:
    host: redis
    port: 6379
    password: password
  session:
    store-type: redis
    timeout: 3600
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    url: jdbc:mariadb://mariadb:3306/spring_dev
    password: root!
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: 'true'
